services:
    webserver:
        build:
            context: ./web-server
            dockerfile: Dockerfile
        container_name: wiki-stats-webserver-${ENV}
        ports:
            - "4321:4321"
        environment:
            NODE_ENV: production
            REDIS_HOST: redis
            REDIS_PORT: 6379
        env_file:
            - .env
        restart: always
        volumes:
            # Mount the actual paths from .env variables
            - ${DB_WIKIS_DIR}:${DB_WIKIS_DIR}
            - ${GRAPHS_WIKIS_DIR}:${GRAPHS_WIKIS_DIR}
            # - ./wiki-folder/stats:
        depends_on:
            - redis
            - rabbitmq
            - sp-server
        profiles: ["prod"]
    sp-server:
        build:
            context: ./WikiGame
            dockerfile: Dockerfile
        container_name: wiki-stats-sp-server-${ENV}
        ports:
            - "1870:1870"
        environment:
            RUST_LOG: info
        env_file:
            - .env
        restart: always
        volumes:
            - ${DB_WIKIS_DIR}:${DB_WIKIS_DIR}
            - ./logs:/app/logs
        profiles: ["prod"]
        command: [
            "--host", "0.0.0.0",
            "--port", "1870",
            "--db-path", "${DB_WIKIS_DIR}",
            "--logfile", "/app/logs/wiki-stats-sp-server.log",
        ]
    redis:
        image: redis:8
        container_name: redis
        ports:
            - "6379:6379"
        profiles: ["dev", "prod"]

    rabbitmq:
        image: rabbitmq:4-management
        container_name: rabbitmq
        ports:
            - "5672:5672"   # AMQP (Celery connects here)
            - "15672:15672" # RabbitMQ Management GUI
            #    environment:
            #      RABBITMQ_DEFAULT_USER: myuser
            #      RABBITMQ_DEFAULT_PASS: mypassword
        volumes:
            - ./task-scheduling/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
        profiles: ["dev", "prod"]